package tui

import (
	"encoding/json"
	"flag"
	"slices"
	"testing"
	"time"

	"github.com/grubless/grubless-cli/internal/golden"
)

// The inputs here — screens and key sequences — were generated by the TS
// build this CLI was first written in, with its clock pinned to fixedNow.
//
// terminal.json's expectations are still the TS's own. render.json's and
// reduce.json's were too, until the Transactions tab: that tab exists only in
// the Go build, so from commit 3a9f0d5 on those two files' *expected outputs*
// are Go's, regenerated with
//
//	go test ./internal/tui -run 'Render|Reduce' -update
//
// Before they were switched over, every difference from the TS was checked
// to be the new tab and nothing else: 180 lines across 300 screens, all in
// the tab bar or the help text, and 65 of 300 key sequences, each diverging
// at the step that entered the new tab. So until someone runs -update again,
// these still pin everything else to the TS's behaviour.
var fixedNow = time.Date(2026, 8, 9, 4, 0, 0, 0, time.UTC)

var update = flag.Bool("update", false, "rewrite the expected outputs in testdata/render.json.gz and reduce.json.gz from this build")

func TestKeysAndWidthsMatchTS(t *testing.T) {
	var g struct {
		DecodeKeys [][2]json.RawMessage `json:"decodeKeys"`
		Truncate   [][4]json.RawMessage `json:"truncate"`
	}
	golden.Load(t, "testdata/terminal.json.gz", &g)

	for _, c := range g.DecodeKeys {
		var chunk string
		var want []struct {
			Name string `json:"name"`
			Ctrl bool   `json:"ctrl"`
		}
		_ = json.Unmarshal(c[0], &chunk)
		_ = json.Unmarshal(c[1], &want)
		got := DecodeKeys(chunk)
		if len(got) != len(want) {
			t.Errorf("DecodeKeys(%q) = %v, want %v", chunk, got, want)
			continue
		}
		for i := range got {
			if got[i].Name != want[i].Name || got[i].Ctrl != want[i].Ctrl {
				t.Errorf("DecodeKeys(%q)[%d] = %v, want %v", chunk, i, got[i], want[i])
			}
		}
	}
	for _, c := range g.Truncate {
		var text, want string
		var width, visible int
		_ = json.Unmarshal(c[0], &text)
		_ = json.Unmarshal(c[1], &width)
		_ = json.Unmarshal(c[2], &want)
		_ = json.Unmarshal(c[3], &visible)
		if got := Truncate(text, width); got != want {
			t.Errorf("Truncate(%q, %d) = %q, want %q", text, width, got, want)
		}
		if got := VisibleWidth(text); got != visible {
			t.Errorf("VisibleWidth(%q) = %d, want %d", text, got, visible)
		}
	}
}

func TestRenderMatchesTS(t *testing.T) {
	Now = func() time.Time { return fixedNow }
	defer func() { Now = time.Now }()

	var screens []struct {
		State  State    `json:"state"`
		Width  int      `json:"width"`
		Height int      `json:"height"`
		Lines  []string `json:"lines"`
	}
	golden.Load(t, "testdata/render.json.gz", &screens)

	if *update {
		var raw []map[string]json.RawMessage
		golden.Load(t, "testdata/render.json.gz", &raw)
		for i, s := range screens {
			raw[i]["lines"], _ = json.Marshal(Render(s.State, s.Width, s.Height))
		}
		golden.Save(t, "testdata/render.json.gz", raw)
		return
	}

	for i, s := range screens {
		got := Render(s.State, s.Width, s.Height)
		if slices.Equal(got, s.Lines) {
			continue
		}
		t.Errorf("screen #%d (%dx%d, tab %s):", i, s.Width, s.Height, s.State.Tab)
		for j := 0; j < max(len(got), len(s.Lines)); j++ {
			var a, b string
			if j < len(got) {
				a = got[j]
			}
			if j < len(s.Lines) {
				b = s.Lines[j]
			}
			if a != b {
				t.Errorf("  line %d\n   got: %q\n  want: %q", j, a, b)
			}
		}
	}
}

func TestReduceMatchesTS(t *testing.T) {
	type projection struct {
		EntityIndex int     `json:"entityIndex"`
		Selected    *string `json:"selected"`
		Tab         Tab     `json:"tab"`
		Offset      int     `json:"offset"`
		Cursor      int     `json:"cursor"`
		Loading     bool    `json:"loading"`
		Message     *string `json:"message"`
		MessageKind string  `json:"messageKind"`
		Syncing     bool    `json:"syncing"`
		ShowHelp    bool    `json:"showHelp"`
		Quit        bool    `json:"quit"`
		Range       string  `json:"range"`
		Holdings    int     `json:"holdings"`
	}
	var sequences []struct {
		Start    State `json:"start"`
		Viewport int   `json:"viewport"`
		Steps    []struct {
			Key struct {
				Name string `json:"name"`
				Ctrl bool   `json:"ctrl"`
			} `json:"key"`
			Action Action     `json:"action"`
			State  projection `json:"state"`
		} `json:"steps"`
	}
	golden.Load(t, "testdata/reduce.json.gz", &sequences)

	if *update {
		var raw []map[string]json.RawMessage
		golden.Load(t, "testdata/reduce.json.gz", &raw)
		for i, seq := range sequences {
			state := seq.Start
			steps := make([]map[string]any, len(seq.Steps))
			for j, step := range seq.Steps {
				var action Action
				state, action = Reduce(state, Key{Name: step.Key.Name, Ctrl: step.Key.Ctrl}, seq.Viewport)
				steps[j] = map[string]any{"key": step.Key, "action": action, "state": projectForGolden(state)}
			}
			raw[i]["steps"], _ = json.Marshal(steps)
		}
		golden.Save(t, "testdata/reduce.json.gz", raw)
		return
	}

	project := func(s State) projection {
		p := projection{
			EntityIndex: s.EntityIndex, Tab: s.Tab, Offset: s.Offset, Cursor: s.Cursor, Loading: s.Loading,
			Message: s.Message, MessageKind: s.MessageKind, Syncing: s.Syncing, ShowHelp: s.ShowHelp,
			Quit: s.Quit, Range: string(s.Range), Holdings: len(s.Data.Holdings),
		}
		if s.SelectedEntity != nil {
			p.Selected = &s.SelectedEntity.ID
		}
		return p
	}
	str := func(p *string) string {
		if p == nil {
			return "<nil>"
		}
		return *p
	}

	for i, seq := range sequences {
		state := seq.Start
		for j, step := range seq.Steps {
			next, action := Reduce(state, Key{Name: step.Key.Name, Ctrl: step.Key.Ctrl}, seq.Viewport)
			got, want := project(next), step.State
			if action != step.Action || str(got.Selected) != str(want.Selected) || str(got.Message) != str(want.Message) {
				t.Fatalf("sequence #%d step %d (%v): action %s selected %s message %s, want %s %s %s",
					i, j, step.Key, action, str(got.Selected), str(got.Message), step.Action, str(want.Selected), str(want.Message))
			}
			got.Selected, want.Selected, got.Message, want.Message = nil, nil, nil, nil
			if got != want {
				t.Fatalf("sequence #%d step %d (%v):\n got: %+v\nwant: %+v", i, j, step.Key, got, want)
			}
			state = next
		}
	}
}

// projectForGolden is the reduce test's projection, for -update: the fields
// navigation touches, named as the TS generator named them.
func projectForGolden(s State) map[string]any {
	var selected *string
	if s.SelectedEntity != nil {
		selected = &s.SelectedEntity.ID
	}
	return map[string]any{
		"entityIndex": s.EntityIndex, "selected": selected, "tab": s.Tab, "offset": s.Offset, "cursor": s.Cursor,
		"loading": s.Loading, "message": s.Message, "messageKind": s.MessageKind, "syncing": s.Syncing,
		"showHelp": s.ShowHelp, "quit": s.Quit, "range": s.Range, "holdings": len(s.Data.Holdings),
	}
}

// TestRenderInvariants holds every fixture screen, in both themes, to the
// frame contract the painter relies on: exactly `height` lines, none wider
// than the terminal. The fixtures include the awkward sizes (a 1-row
// terminal, a 20-column one) where a layout's arithmetic goes negative.
func TestRenderInvariants(t *testing.T) {
	Now = func() time.Time { return fixedNow }
	defer func() { Now = time.Now }()

	var screens []struct {
		State  State `json:"state"`
		Width  int   `json:"width"`
		Height int   `json:"height"`
	}
	golden.Load(t, "testdata/render.json.gz", &screens)
	for i, sc := range screens {
		for _, theme := range []string{ThemeTerminal, ThemeCypher} {
			st := sc.State
			st.Theme, st.TrueColour = theme, true
			lines := Render(st, sc.Width, sc.Height)
			if len(lines) != sc.Height {
				t.Errorf("screen #%d (%s, %dx%d): %d lines", i, theme, sc.Width, sc.Height, len(lines))
			}
			for j, line := range lines {
				if w := VisibleWidth(line); w > sc.Width {
					t.Errorf("screen #%d (%s, %dx%d) line %d: %d wide", i, theme, sc.Width, sc.Height, j, w)
				}
			}
		}
	}
}
